export interface Session {
  time: string
  title: string
  location: string
  category: "education" | "culinary" | "beverage" | "innovation" | "discovery" | "tour" | "event" | "other"
}

function categorize(title: string, location: string): Session["category"] {
  if (location.startsWith("Room S")) return "education"
  if (location.includes("Culinary")) return "culinary"
  if (location.includes("Beverage")) return "beverage"
  if (location.includes("Innovation")) return "innovation"
  if (location.includes("Discovery")) return "discovery"
  if (title.includes("Tour")) return "tour"
  if (title.includes("Reception") || title.includes("Networking") || title.includes("Party") || title.includes("Meetup")) return "event"
  return "other"
}

function s(time: string, title: string, location: string): Session {
  return { time, title, location, category: categorize(title, location) }
}

export const nraSessions: Record<string, Session[]> = {
  sat: [
    s("9:30 AM - 5:00 PM", "Plate Drop Prize Game", "Grand Concourse"),
    s("9:30 AM - 5:00 PM", "Show Exhibits Open", "All Halls"),
    s("9:30 AM - 5:00 PM", "Show Store Open", "Grand Concourse"),
    s("10:00 AM - 4:00 PM", "Massages at The Sustainability & Wellness Lounge", "Sustainability Lounge"),
    s("10:30 AM - 11:00 AM", "Adult Beverage Demo - TBA", "The Beverage Room Stage - 13955"),
    s("10:30 AM - 11:00 AM", "Quick Tips for Navigating the Show & New Attendees Meetup", "Innovation Theater - North Hall - 5577"),
    s("10:30 AM - 11:15 AM", "Culinary Demo with Chef Rick Bayless", "The Culinary Experience - 12448"),
    s("11:00 AM - 12:00 PM", "Foodservice Fashion Showcase", "Discovery Theater - South Hall - 2693"),
    s("11:00 AM - 12:10 PM", "See, Touch, Taste Tours - North Hall", "North Hall"),
    s("11:15 AM - 11:45 AM", "Book Signing with Chef Rick Bayless", "The Culinary Experience - 12448"),
    s("11:30 AM - 12:00 PM", "Beyond the Dining Room: Diversifying Commerce to Build Profit Resilience", "Innovation Theater - North Hall - 5577"),
    s("11:30 AM - 12:00 PM", "Crafting Winning Drink Promotions", "The Beverage Room Stage - 13955"),
    s("11:45 AM - 12:45 PM", "Welcome Expo + Education Attendees: An Exclusive Networking Session", "South Building, 400 Level Foyer"),
    s("12:00 PM - 12:45 PM", "Farm to Table: Women Powering the Future of Food", "The Culinary Experience - 12448"),
    s("12:30 PM - 1:00 PM", "Adult Beverage Demo - TBA", "The Beverage Room Stage - 13955"),
    s("12:30 PM - 1:40 PM", "Convenience Tour", "Multiple Locations"),
    s("1:00 PM - 1:30 PM", "Turning Empty Seats into Revenue: Bar Owners Break Down the Gaming Opportunity", "Discovery Theater - South Hall - 2693"),
    s("1:00 PM - 1:45 PM", "Clout to Covers: Influencer Deals That Drive Reservations", "Room S504 - South Building - 5th Floor"),
    s("1:00 PM - 1:45 PM", "Harnessing Uncertainty: Turning Market Shifts Into Momentum", "Room S404 - South Building - 4th Floor"),
    s("1:00 PM - 1:45 PM", "Money Matters: Food Choices in the New Financial Reality", "Room S403 - South Building - 4th Floor"),
    s("1:00 PM - 1:45 PM", "Stronger Restaurant Teams: Clarifying Roles, Driving Accountability, and Building a Culture That Retains Talent", "Room S503 - South Building - 5th Floor"),
    s("1:00 PM - 1:45 PM", "The 2026 State of the Industry: Position Yourself for Success in the Face of Uncertainty", "Room S502 - South Building - 5th Floor"),
    s("1:00 PM - 2:10 PM", "See, Touch, Taste Tours - South Hall", "South Hall"),
    s("1:00 PM - 2:30 PM", "FABI Awardees Tasting", "The Culinary Experience - 12448"),
    s("1:30 PM - 2:00 PM", "The Power of Events: Turning Restaurant Moments into Predictable Revenue", "Innovation Theater - North Hall - 5577"),
    s("2:00 PM - 2:30 PM", "Discovery Theater Session - TBA", "Discovery Theater - South Hall - 2693"),
    s("2:00 PM - 2:30 PM", "Popping Boba - For Adults Too!", "The Beverage Room Stage - 13955"),
    s("2:00 PM - 2:45 PM", "AI + Predictive Marketing: Smarter Campaigns, Less Discounting", "Room S404 - South Building - 4th Floor"),
    s("2:00 PM - 2:45 PM", "Before Disaster Hits the Kitchen: Practical Preparedness and Recovery Strategies for Restaurant Operators", "Room S504 - South Building - 5th Floor"),
    s("2:00 PM - 2:45 PM", "Convert Wasted Potential Into Profits", "Room S502 - South Building - 5th Floor"),
    s("2:00 PM - 2:45 PM", "Menu Profit Playbook: 3 Field Examples to $60K+ Profit", "Room S403 - South Building - 4th Floor"),
    s("2:00 PM - 2:45 PM", "Training in the TikTok Era: Micro-Learning and New Expectations for Workforce Success", "Room S503 - South Building - 5th Floor"),
    s("2:30 PM - 3:00 PM", "Innovation Theater Session - TBA", "Innovation Theater - North Hall - 5577"),
    s("3:00 PM - 3:30 PM", "Discovery Theater Session - TBA", "Discovery Theater - South Hall - 2693"),
    s("3:00 PM - 4:10 PM", "See, Touch, Taste Tours - Lakeside Center", "Lakeside Center"),
    s("3:15 PM - 4:00 PM", "Culinary Demo with Chef Leah Cohen", "The Culinary Experience - 12448"),
    s("3:30 PM - 4:00 PM", "Beyond Food and Beverage: Turning Food, Drinks & Experiences into Profit and Community", "The Beverage Room Stage - 13955"),
    s("3:30 PM - 4:00 PM", "Innovation Theater Session - TBA", "Innovation Theater - North Hall - 5577"),
    s("4:00 PM - 4:45 PM", "The Real Power of Technology and Guest Experience to Revolutionize Foodservice", "Discovery Theater - South Hall - 2693"),
    s("5:00 PM - 6:00 PM", "International Reception", "South Building"),
  ],
  sun: [
    s("9:30 AM - 5:00 PM", "Plate Drop Prize Game", "Grand Concourse"),
    s("9:30 AM - 5:00 PM", "Show Exhibits Open", "All Halls"),
    s("9:30 AM - 5:00 PM", "Show Store Open", "Grand Concourse"),
    s("9:45 AM - 12:15 PM", "Risk, Reward & Revenue: Restaurant Catering Workshop", "Room S404 - South Building - 4th Floor"),
    s("10:00 AM - 10:45 AM", "Culinary Demo with Chef Chris Cosentino", "The Culinary Experience - 12448"),
    s("10:00 AM - 11:10 AM", "Tech Innovations Tour", "Multiple Locations"),
    s("10:00 AM - 4:00 PM", "Massages at The Sustainability & Wellness Lounge", "Sustainability Lounge"),
    s("10:30 AM - 11:00 AM", "App-Free Loyalty: Lessons from Portillo's Winning Guest Engagement and Retention Strategy", "Innovation Theater - North Hall - 5577"),
    s("11:00 AM - 11:30 AM", "Beverage-Forward Menus: How Sips Are Steering Flavor Innovation", "The Beverage Room Stage - 13955"),
    s("11:00 AM - 11:30 AM", "Discovery Theater Session - TBA", "Discovery Theater - South Hall - 2693"),
    s("11:00 AM - 12:10 PM", "See, Touch, Taste Tours - Lakeside Center", "Lakeside Center"),
    s("11:30 AM - 12:00 PM", "How to Win (or Lose) Business at Every Step of the Guest Journey", "Innovation Theater - North Hall - 5577"),
    s("11:30 AM - 12:15 PM", "4 Disruptors Driving Menu Trends and Innovation", "The Culinary Experience - 12448"),
    s("12:00 PM - 12:30 PM", "Adult Beverage Session - TBA", "The Beverage Room Stage - 13955"),
    s("12:45 PM - 1:15 PM", "Book Signing with Chef Michael Mina", "The Culinary Experience - 12448"),
    s("1:00 PM - 2:10 PM", "See, Touch, Taste Tours - North Hall", "North Hall"),
    s("1:00 PM - 2:30 PM", "Keynote '26", "Grand Ballroom, S100, South Building Level 1"),
    s("1:15 PM - 2:45 PM", "FABI Awardees Tasting", "The Culinary Experience - 12448"),
    s("2:00 PM - 2:30 PM", "Adult Beverage Demo - TBA", "The Beverage Room Stage - 13955"),
    s("3:00 PM - 3:30 PM", "Beyond Visibility: Driving Revenue Through Real-Time Operations Execution", "Innovation Theater - North Hall - 5577"),
    s("3:00 PM - 3:45 PM", "10 Ways to Cut Food Costs Without Cutting Flavor", "Room S403 - South Building - 4th Floor"),
    s("3:00 PM - 3:45 PM", "Cook Up Financial Security: Safeguard Your Restaurant from Lawsuits & Taxes", "Room S502 - South Building - 5th Floor"),
    s("3:00 PM - 3:45 PM", "Frictionless or Forgotten: Rebuilding the Guest Digital Funnel", "Room S504 - South Building - 5th Floor"),
    s("3:00 PM - 3:45 PM", "From Sidewalk to Smartphone: How Grassroots Marketing and AI Can Transform Restaurant Growth", "Room S404 - South Building - 4th Floor"),
    s("3:00 PM - 3:45 PM", "Training Without a Training Department: Practical Strategies for Restaurants", "Room S503 - South Building - 5th Floor"),
    s("3:00 PM - 4:10 PM", "Convenience Tour", "Multiple Locations"),
    s("3:00 PM - 4:10 PM", "See, Touch, Taste Tours - South Hall", "South Hall"),
    s("3:15 PM - 4:00 PM", "Culinary Demo with Chef Barton Seaver and Chef Andrew Zimmern", "The Culinary Experience - 12448"),
    s("3:30 PM - 4:00 PM", "Adult Beverage Demo - TBA", "The Beverage Room Stage - 13955"),
    s("3:30 PM - 4:00 PM", "Lessons from the Top: Foodservice Industry Leaders Share their Path to Success", "Discovery Theater - South Hall - 2693"),
    s("4:00 PM - 4:30 PM", "Celebrating the Future of Foodservice: A Networking Event for Young Professionals", "Discovery Theater - South Hall - 2693"),
    s("4:00 PM - 4:40 PM", "Book Signing with Chef Barton Seaver and Chef Andrew Zimmern", "The Culinary Experience - 12448"),
    s("4:00 PM - 4:45 PM", "Community-First Marketing in a Tech-Driven World", "Room S504 - South Building - 5th Floor"),
    s("4:00 PM - 4:45 PM", "Email vs Social: Where Restaurant Marketing Drives Revenue", "Room S403 - South Building - 4th Floor"),
    s("4:00 PM - 4:45 PM", "Empowering New Hires to Thrive from Day One", "Room S503 - South Building - 5th Floor"),
    s("4:00 PM - 4:45 PM", "How to Turn Followers into Guests in the New Era of Social Media Marketing", "Room S404 - South Building - 4th Floor"),
    s("4:00 PM - 4:45 PM", "Smarter Staffing: How Technology Is Solving Today's Restaurant Labor Challenges", "Innovation Theater - North Hall - 5577"),
    s("4:00 PM - 4:45 PM", "The Adults' Table: Winning Over the 50+ Diner", "Room S502 - South Building - 5th Floor"),
  ],
  mon: [
    s("9:30 AM - 12:00 PM", "Workshop: AI Essentials for Operators", "Room S404 - South Building - 4th Floor"),
    s("9:30 AM - 5:00 PM", "Plate Drop Prize Game", "Grand Concourse"),
    s("9:30 AM - 5:00 PM", "Show Exhibits Open", "All Halls"),
    s("9:30 AM - 5:00 PM", "Show Store Open", "Grand Concourse"),
    s("10:00 AM - 10:45 AM", "Cooking Up Menu Magic with Award-Winning FABI Favorites", "The Culinary Experience - 12448"),
    s("10:00 AM - 11:10 AM", "Tech Innovations Tour", "Multiple Locations"),
    s("10:00 AM - 4:00 PM", "Massages at The Sustainability & Wellness Lounge", "Sustainability Lounge"),
    s("10:30 AM - 11:00 AM", "Operator Meetup: How To Win the Guest Without Killing Margin", "Innovation Theater - North Hall - 5577"),
    s("10:45 AM - 11:15 AM", "Adult Beverage Demo - TBA", "The Beverage Room Stage - 13955"),
    s("10:45 AM - 11:45 AM", "FABI Favorites Tasting", "The Culinary Experience - 12448"),
    s("11:00 AM - 12:00 PM", "Packaging Innovation Showcase", "Discovery Theater - South Hall - 2693"),
    s("11:00 AM - 12:10 PM", "See, Touch, Taste Tours - South Hall", "South Hall"),
    s("11:30 AM - 12:00 PM", "AI That Works: Real Operators, Real Wins", "Innovation Theater - North Hall - 5577"),
    s("12:00 PM - 12:30 PM", "Culinary Demo with Chef Michael Mina", "The Culinary Experience - 12448"),
    s("12:00 PM - 1:15 PM", "Pouring Profits with Winning Draft Strategies", "The Beverage Room Stage - 13955"),
    s("12:30 PM - 1:00 PM", "Innovation Theater Session - TBA", "Innovation Theater - North Hall - 5577"),
    s("1:00 PM - 2:00 PM", "Featured Session with Technomic - Get it While it's Hot: Driving Demand with LTOs", "Grand Ballroom, S100, South Building Level 1"),
    s("1:00 PM - 2:10 PM", "See, Touch, Taste Tours - Lakeside Center", "Lakeside Center"),
    s("1:30 PM - 2:00 PM", "Discovery Theater Session - TBA", "Discovery Theater - South Hall - 2693"),
    s("1:45 PM - 2:15 PM", "Winning Adult Beverage Sales in 2026", "The Beverage Room Stage - 13955"),
    s("2:00 PM - 2:30 PM", "Rule Your World: Why Payments Independence Is the New Competitive Advantage for Restaurants", "Innovation Theater - North Hall - 5577"),
    s("2:00 PM - 2:45 PM", "Culinary Demo with Chef Jet Tila", "The Culinary Experience - 12448"),
    s("2:30 PM - 3:00 PM", "Discovery Theater Session - TBA", "Discovery Theater - South Hall - 2693"),
    s("2:30 PM - 3:15 PM", "7 Numbers Every Restaurateur Needs to Know", "Room S404 - South Building - 4th Floor"),
    s("2:30 PM - 3:15 PM", "A Year of GLP-1s: Consumer Behavior That's Here to Stay", "Room S403 - South Building - 4th Floor"),
    s("2:30 PM - 3:15 PM", "AI in Hospitality: Keeping the Human Connection", "Room S502 - South Building - 5th Floor"),
    s("2:30 PM - 3:15 PM", "Cultural Intelligence as a Growth Strategy for Modern Restaurant Brands", "Room S504 - South Building - 5th Floor"),
    s("2:30 PM - 3:15 PM", "Expo + Education Session: TBA", "Room S503 - South Building - 5th Floor"),
    s("2:30 PM - 3:15 PM", "Solutions Spotlight: Health & Safety", "Discovery Theater - South Hall - 2693"),
    s("2:45 PM - 3:15 PM", "Hemp Beverages: The Legal and Regulatory Landscape Today and the Road Ahead", "The Beverage Room Stage - 13955"),
    s("3:00 PM - 3:30 PM", "The AI Teammate: Making Daily Ops Feel Less Like a Guessing Game", "Innovation Theater - North Hall - 5577"),
    s("3:00 PM - 4:10 PM", "See, Touch, Taste Tours - North Hall", "North Hall"),
    s("3:30 PM - 4:15 PM", "Connecting Business with Policy to Tackle Our Industry's Immigration Reality", "Discovery Theater - South Hall - 2693"),
    s("3:30 PM - 4:15 PM", "Culinary Demo with Chef Sarah Grueneberg", "The Culinary Experience - 12448"),
    s("3:30 PM - 4:15 PM", "Keeping Customers Curious: Bold Flavors and the Quest for Quality", "Room S504 - South Building - 5th Floor"),
    s("3:30 PM - 4:15 PM", "Making Hospitality Hospitable (Again)", "Room S502 - South Building - 5th Floor"),
    s("3:30 PM - 4:15 PM", "Sidestep the Sticker Shock: How to Keep Menus Affordable Amidst Higher Food Costs and Labor Pressure", "Room S403 - South Building - 4th Floor"),
    s("3:30 PM - 4:15 PM", "The Restaurant Loyalty Roadmap for Lasting Customer Growth", "Room S404 - South Building - 4th Floor"),
    s("3:30 PM - 4:15 PM", "Thriving Through Challenges: A Discussion with Foodservice Leaders Driving Real Growth", "Room S503 - South Building - 5th Floor"),
    s("3:45 PM - 4:15 PM", "Craft Spirits on the Menu", "The Beverage Room Stage - 13955"),
    s("4:00 PM - 4:30 PM", "Innovation Theater Session - TBA", "Innovation Theater - North Hall - 5577"),
    s("8:00 PM - 11:00 PM", "Restaurant Show After Party (additional registration required)", "Off-Site"),
  ],
  tue: [
    s("9:30 AM - 3:00 PM", "Plate Drop Prize Game", "Grand Concourse"),
    s("9:30 AM - 3:00 PM", "Show Exhibits Open", "All Halls"),
    s("9:30 AM - 3:00 PM", "Show Store Open", "Grand Concourse"),
    s("10:00 AM - 10:45 AM", "Personalization Strategies for Exceptional Guest Experiences", "Discovery Theater - South Hall - 2693"),
    s("10:30 AM - 11:00 AM", "Innovation Theater Session - TBA", "Innovation Theater - North Hall - 5577"),
    s("11:00 AM - 11:30 AM", "Adult Beverage Demo - TBA", "The Beverage Room Stage - 13955"),
    s("11:00 AM - 11:30 AM", "Discovery Theater Session - TBA", "Discovery Theater - South Hall - 2693"),
    s("11:30 AM - 12:00 PM", "Mochi Innovation: Driving Business Success with Craveable Textures and Globally Inspired Comfort Foods", "Innovation Theater - North Hall - 5577"),
    s("12:00 PM - 12:30 PM", "Discovery Theater Session - TBA", "Discovery Theater - South Hall - 2693"),
    s("12:00 PM - 12:30 PM", "Fluid Motion: Smarter Bar Techniques and Design to Improve Efficiency and Execution", "The Beverage Room Stage - 13955"),
    s("12:30 PM - 1:00 PM", "Innovation Theater Session - TBA", "Innovation Theater - North Hall - 5577"),
  ],
}

export const sessionCategories = [
  { key: "all", label: "All" },
  { key: "education", label: "Education" },
  { key: "culinary", label: "Culinary" },
  { key: "beverage", label: "Beverage" },
  { key: "innovation", label: "Innovation" },
  { key: "discovery", label: "Discovery" },
  { key: "tour", label: "Tours" },
  { key: "event", label: "Events" },
] as const
